{% set name = "openvino-telemetry" %}
{% set version = "2022.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 41eec1f6a9bbb528971bea8cf545ab9627e80e67522345fe77d2df3a2d3db73e

build:
  number: 0
  entry_points:
    - opt_in_out = openvino_telemetry.opt_in_out:main
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - requests >=2.20.0
  run:
    - python >=3.6
    - requests >=2.20.0

test:
  imports:
    - openvino_telemetry
    - openvino_telemetry.backend
    - openvino_telemetry.utils
  commands:
    - opt_in_out --help

about:
  home: https://github.com/openvinotoolkit/telemetry
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: OpenVINO™ Telemetry package for sending statistics with user's consent, used in combination with other OpenVINO™ packages.
  doc_url: https://pypi.org/project/openvino-telemetry/#description
  dev_url: https://github.com/openvinotoolkit/telemetry

extra:
  recipe-maintainers:
    - ilya-lavrenov
