{% set name = "openvino-telemetry" %}
{% set version = "2024.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6df9a8f499e75d893d0bece3c272e798109f0bd40d1eb2488adca6a0da1d9b9f

build:
  number: 0
  entry_points:
    - opt_in_out = openvino_telemetry.opt_in_out:main
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - openvino_telemetry
    - openvino_telemetry.backend
    - openvino_telemetry.utils
  commands:
    - opt_in_out --help

about:
  home: https://github.com/openvinotoolkit/telemetry
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: OpenVINO™ Telemetry package for sending statistics with user's consent, used in combination with other OpenVINO™ packages.
  doc_url: https://pypi.org/project/openvino-telemetry/#description
  dev_url: https://github.com/openvinotoolkit/telemetry

extra:
  recipe-maintainers:
    - ilya-lavrenov
    - popovaan
